### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by ariskk** [ariskk/zio-raft#11]
As it currently stands and due to the multi-module structure, the project would be published in jars: `core`, `server` and `rocksdb`. The names would be very confusing and I think only `core` would actually work.

@liguobin233 @jxnu-liguobin The project cannot be currently published by just running the existing `sbt release` command. Given that the modules do not make much sense as stand-alone jars, I would recommend a small refactoring to bring all the packages under a single module. Then I can publish `zio-raft` as a stand-alone.

Would that work for your use case?

I do not have much time to do that, but if you open a PR with that bit I will do the rest.

**Comment by jxnu-liguobin** [comment]
> As it currently stands and due to the multi-module structure, the project would be published in jars: `core`, `server` and `rocksdb`. The names would be very confusing and I think only `core` would actually work.
> 
> @liguobin233 @jxnu-liguobin The project cannot be currently published by just running the existing `sbt release` command. Given that the modules do not make much sense as stand-alone jars, I would recommend a small refactoring to bring all the packages under a single module. Then I can publish `zio-raft` as a stand-alone.
> 
> Would that work for your use case?
> 
> I do not have much time to do that, but if you open a PR with that bit I will do the rest.

yes, I will do it, and server and rocksdb  maybe should move to examples?

**Comment by ariskk** [comment]
Actually, they don't have to. If you just want the algorithm, we can just add publish `zio-raft-core` and leave the others as it. In this case, we leave the structure as is and then we skip `server`, `rocksdb` and `root`. We just need to add a name so that it is published as `zio-raft-core` or just `zio-raft` and not just `core`.

**Comment by ariskk** [comment]
@jxnu-liguobin I have published `zio-raft`.
I ran on ammonite 
```
@ import $ivy.`com.ariskk::zio-raft:0.3.0`
```
and it fetched the dependency. Please have a look.

**Comment by jxnu-liguobin** [comment]
> com.ariskk::zio-raft:0.3.0

Thank you very much. I can see the it, but, at present, I don't have time to test more. If there are problems later, I will create RP.

Thanks again. 😃
